# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/tim_c/CK24/CKiller24.srcs/sources_1/ip/dataRam/dataRam.xci
# IP: The module: 'dataRam' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tim_c/CK24/CKiller24.srcs/sources_1/ip/dataRam/dataRam_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dataRam'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/tim_c/CK24/CKiller24.srcs/sources_1/ip/dataRam/dataRam.xci
# IP: The module: 'dataRam' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tim_c/CK24/CKiller24.srcs/sources_1/ip/dataRam/dataRam_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dataRam'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
