# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sa/tmc/CK24/CKiller24.srcs/sources_1/ip/progmem/progmem.xci
# IP: The module: 'progmem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sa/tmc/CK24/CKiller24.srcs/sources_1/ip/progmem/progmem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'progmem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/sa/tmc/CK24/CKiller24.srcs/sources_1/ip/progmem/progmem.xci
# IP: The module: 'progmem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sa/tmc/CK24/CKiller24.srcs/sources_1/ip/progmem/progmem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'progmem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
