# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/tmc/Keyboard.xdc

# IP: ip/progmem/progmem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==progmem || ORIG_REF_NAME==progmem} -quiet] -quiet
